name: Cypress Testing in git
on: [push]
jobs:
  CypressTest:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress with Cucumber
        uses: cypress-io/github-action@v4.2.0
        with: 
          browser: chrome
          install-command:  npm ci

      - name: Install Allure
        run: npm install -g allure-commandline --save-dev && npm i -D @shelex/cypress-allure-plugin
      
      - name: Generate Report
        run: npm run test

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-allure-report
          path: /home/runner/work/allureGitHubActions/allureGitHubActions/allure-report
          
      - name: Get Allure history
        uses: actions/checkout@v3.3.0
        if: always()
        uses: afiore/action-allure-report@v0.1.0

      - name: Allure Report with history
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: ad-m/github-push-action@master
        with:
            github_token: '${{ secrets.GITHUB_TOKEN }}'
            force: true