name: Cypress Testing in git
on:
  push:
  schedule:
    - cron: '* * * * 4'  # At 01:00 on Mondays.
jobs:
  CypressTest:
    runs-on:  ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Cypress with Cucumber
        uses: cypress-io/github-action@v4.2.0
        with: 
          browser: chrome
          install-command:  npm ci

      - name: Install Allure
        run: npm install -g allure-commandline --save-dev && npm i -D @shelex/cypress-allure-plugin
      
      - name: Generate Report
        run: npm run test

      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-allure-report
          path: /home/runner/work/allureGitHubActions/allureGitHubActions/allure-report

      - name: Get Allure history
        uses: actions/checkout@v3.3.0
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report with history
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
